C:\Program Files (x86)\Inflectra\Rapise\Engine\InstrumentJS\NodeWScript.js 6.0
SeS Player Starting...
Rapise Version:8.1.29.56
Verbose level:1
###Scenario_GetDoctorById_200 (-2)
###Play RVL@Scenario_GetDoctorById_200 (1)
Attaching to spreadsheet : true : C:\Users\shahana.shajahan\RapiseTest\RapiseTestSamples\Sub_Test_1\Scenario_GetDoctorById_200\Main.rvl.xlsx
Playing script: Script: C:\Users\shahana.shajahan\RapiseTest\RapiseTestSamples\Sub_Test_1\Scenario_GetDoctorById_200\Main.rvl.xlsx:RVL, 57 source rows 0 errors
Looking for object:RVL
###Play createDoctor_200@Scenario_GetDoctorById_200 (1)
Attaching to spreadsheet : true : C:\Users\shahana.shajahan\RapiseTest\RapiseTestSamples\Sub_Test_1\Scenario_GetDoctorById_200\Main.rvl.xlsx
Playing script: Script: C:\Users\shahana.shajahan\RapiseTest\RapiseTestSamples\Sub_Test_1\Scenario_GetDoctorById_200\Main.rvl.xlsx:createDoctor_200, 107 source rows 0 errors
Looking for object:Tester
###When Doctor is created (-2)
Looking for object:Scenario_CreateDoctor200_POST_CreateDoctor_200
Scenario_CreateDoctor200_POST_CreateDoctor_200.DoExecute()
DoExecute: Error Returned from Server '{"success":false,"errors":["Aadhaar already present in database"]}'
###Scenario_CreateDoctor200_POST_CreateDoctor_200.DoExecute() (0)
Test stopped on error: Scenario_CreateDoctor200_POST_CreateDoctor_200.DoExecute()
FAILURE IN SCRIPT: Error calling function createDoctor: 500
###Error calling function createDoctor: 500 (0)
Test stopped on error: Error calling function createDoctor: 500
###Scenario_GetDoctorById_200 (0)
Test execution done
##############################################################
Test Fail: Scenario_GetDoctorById_200,  (Passed:2 Failed:2 Time:1.196s)
Test Session Status: Fail Time: 2.942s
##############################################################
